#!/usr/bin/env python3

from itertools import cycle
from time import sleep
from quick2wire.gpio import pins, Out

with pins.pin(1, direction=Out) as led:
    for v in cycle([1,0]):
        led.value = v
        sleep(0.5)


