#!/usr/bin/env python3

from itertools import cycle
from time import sleep
from quick2wire.gpio import pins, In, Out

with pins.pin(0, direction=In) as button, \
     pins.pin(1, direction=Out) as led:
    print("ready")
    
    for v in cycle([1,0]):
        led.value = v * button.value
        sleep(0.5)
