#!/usr/bin/env python3
import quick2wire.i2c as i2c
from time import sleep
import sys
import random

IODIR=0x00
IPOL=0x01

GPIO_0_ADDRESS = 0x12
GPIO_1_ADDRESS = 0x13
GPIO_ADDRESSES = [GPIO_0_ADDRESS, GPIO_1_ADDRESS]
LED_BITS = [1,3,5,7]

ALL_OFF = 0x00
ALL_OUTPUTS = 0x00

def write_register(bus, register, bits):
  bus.transaction(i2c.writing_bytes(address, register, bits))

def leds_off(bus, register):
  write_register(bus, register, ALL_OFF)
  
def flash_random_led(bus):
  register = random.choice(GPIO_ADDRESSES)
  write_register(bus, register, 1 << random.choice(LED_BITS))
  sleep(random.uniform(0.0, 0.4))
  leds_off(bus, register)

offset = int(sys.argv[1]) if len(sys.argv) > 1 else 0
address = 0x20 + offset

with i2c.I2CMaster() as bus:
  write_register(bus, IODIR, ALL_OUTPUTS)
  write_register(bus, IPOL, ALL_OUTPUTS)
  try:
    while True:
      flash_random_led(bus)
  except KeyboardInterrupt:
    for register in GPIO_ADDRESSES:
      leds_off(bus, register)



